export const USERS: any[] = [
  {
    'id': '0',
    'userFirstName': 'Stephen',
    'userLastName': 'Moreira',
    'penName': 'Nightfall',
    'eMail': 'smoreira1@live.com',
    'phoneNumber': '407-310-8747',
    'country': 'USA',
    'city': 'Orlando',
    'state': 'Florida',
    'dateJoined': '06/21/2017',
    'premiumMember': 'YES',
    'following': [],
    'studios': [],
    'artWork': [],
    'cart': [],
    'viewHistory': [],
    'transactionHistory': [],
    'favorites': [],
    'guid': []
  },
  {
    'id': '1',
    'userFirstName': 'Ruby',
    'userLastName': 'Perez',
    'penName': 'Nightfall',
    'eMail': 'smoreira1@live.com',
    'phoneNumber': '407-310-8747',
    'country': 'USA',
    'city': 'Orlando',
    'state': 'Florida',
    'dateJoined': '06/21/2017',
    'premiumMember': 'YES',
    'following': [],
    'studios': [],
    'artWork': [],
    'cart': [],
    'viewHistory': [],
    'transactionHistory': [],
    'favorites': [],
    'guid': []
  },
  {
    'id': '2',
    'userFirstName': 'Chris',
    'userLastName': 'Andreev',
    'penName': 'Nightfall',
    'eMail': 'smoreira1@live.com',
    'phoneNumber': '407-310-8747',
    'country': 'USA',
    'city': 'Orlando',
    'state': 'Florida',
    'dateJoined': '06/21/2017',
    'premiumMember': 'YES',
    'following': [],
    'studios': [],
    'artWork': [],
    'cart': [],
    'viewHistory': [],
    'transactionHistory': [],
    'favorites': [],
    'guid': []
  },
  {
    'id': '3',
    'userFirstName': 'Kevin',
    'userLastName': 'Marsh',
    'penName': 'Nightfall',
    'eMail': 'smoreira1@live.com',
    'phoneNumber': '407-310-8747',
    'country': 'USA',
    'city': 'Orlando',
    'state': 'Florida',
    'dateJoined': '06/21/2017',
    'premiumMember': 'YES',
    'following': [],
    'studios': [],
    'artWork': [],
    'cart': [],
    'viewHistory': [],
    'transactionHistory': [],
    'favorites': [],
    'guid': []
  },
  {
    'id': '4',
    'userFirstName': 'Stephen',
    'userLastName': 'Moreira',
    'penName': 'Nightfall',
    'eMail': 'smoreira1@live.com',
    'phoneNumber': '407-310-8747',
    'country': 'USA',
    'city': 'Orlando',
    'state': 'Florida',
    'dateJoined': '06/21/2017',
    'premiumMember': 'YES',
    'following': [],
    'studios': [],
    'artWork': [],
    'cart': [],
    'viewHistory': [],
    'transactionHistory': [],
    'favorites': [],
    'guid': []
  },
  {
    'id': '5',
    'userFirstName': 'Stephen',
    'userLastName': 'Moreira',
    'penName': 'Nightfall',
    'eMail': 'smoreira1@live.com',
    'phoneNumber': '407-310-8747',
    'country': 'USA',
    'city': 'Orlando',
    'state': 'Florida',
    'dateJoined': '06/21/2017',
    'premiumMember': 'YES',
    'following': [],
    'studios': [],
    'artWork': [],
    'cart': [],
    'viewHistory': [],
    'transactionHistory': [],
    'favorites': [],
    'guid': []
  },
];
